services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs
    ports:
      - '5432:5432'